// Generated by Wrangler on Sun Jul 07 2024 02:17:05 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	telegram_in_out: KVNamespace;
	TELEGRAM_BOT_TOKEN: "7257452888:AAHuuT8dZzBSqyKlghzxmmr8W0O486-tAAw";
}
