#:schema node_modules/wrangler/config-schema.json
name = "in-out-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

[[kv_namespaces]]
binding = "telegram_in_out"
id = "f77e8fde5a6f435bb6c8ad378885c361"

[vars]
TELEGRAM_BOT_TOKEN = "7257452888:AAHuuT8dZzBSqyKlghzxmmr8W0O486-tAAw"
